server:
  port: 9527

spring:
  application:
    name: cloud-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #路由ID，没有固定的规则要求，但是要求唯一，建议配合服务名
        - id: payment_routh
          #匹配后路由提供的服务调用地址
          #uri: http://localhost:8005
          uri: lb://cloud-payment-service
          predicates:
            #断言，路径相匹配的进行路由
            #- Path=/payment/hystrix/ok/**,
            - Path=/payment/get/**
            #- Cookie=username,liuzhen
            #- Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.bili.com
            #- Method=POST
            #- Query=username,/d+ #要求参数名username并且值为整数才允许路由

        - id: payment_routh2 #路由ID，没有固定的规则要求，但是要求唯一，建议配合服务名
          #匹配后路由提供的服务调用地址
          #uri: http://localhost:8005
          uri: lb://cloud-payment-service
          predicates:
            #断言，路径相匹配的进行路由
            #- Path=/payment/hystrix/error/**
            - Path=/payment/discovery
            # After表示在这个时间后才能进行访问
            #- After=2021-04-25T19:26:12.146+08:00[Asia/Shanghai]

#入驻注册中心配置信息
eureka:
  client:
    #表示将服务注册到eureka
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群注册
      defaultZone: http://${server.eureka1.name}:${server.eureka1.port}/eureka,http://${server.eureka2.name}:${server.eureka2.port}/eureka
  instance:
    #在eureka展示的地址服务信息
    instance-id: gateway9527
    #光标移动访问路径显示IP
    prefer-ip-address: true
