server:
  port: 80


spring:
  application:
    name: feign-consumer-order

#入驻注册中心配置信息
eureka:
  client:
    #表示将服务注册到eureka
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群注册
      defaultZone: http://${server.eureka1.name}:${server.eureka1.port}/eureka,http://${server.eureka2.name}:${server.eureka2.port}/eureka
  instance:
    instance-id: openFeign80
    prefer-ip-address: true

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


logging:
  level:
    #feigne日志监控类，开启日志级别 -debug
    com.study.feign.service.PaymentFeignConfig: debug