server:
  port: 80

spring:
  application:
    name: cloud-hystrix-order

#入驻注册中心配置信息
eureka:
  client:
    #表示将服务注册到eureka
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群注册
      defaultZone: http://${server.eureka1.name}:${server.eureka1.port}/eureka,http://${server.eureka2.name}:${server.eureka2.port}/eureka
  instance:
    instance-id: hystrixOrder80
    prefer-ip-address: true


#开启服务降级处理
feign:
  hystrix:
    enabled: true